_target_: src.models.cora_module.CoraLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.gnn.GNN
  input_size: 1433
  hidden_size: 64
  output_size: 7

# compile model for faster training with pytorch 2.0
compile: false
