# @package _global_

defaults:
  - _self_
  - data: mnist # choose datamodule with `test_dataloader()` for evaluation
  - model: mnist
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: D:\zjclearning\pythonproject\lightning-hydra-template\logs\train\runs\2023-11-14_12-42-04\checkpoints\epoch_008.ckpt
